steps:

- id: "Rodando docker-compose"
  name: 'gcr.io/$PROJECT_ID/docker-compose'
  args: ['-f', 'docker-compose.cloudbuild.yaml', 'up', '-d']  

- id: "Rodando docker ps"
  name: 'gcr.io/cloud-builders/docker'
  args: ['ps']  

- id: "Rodando o soma"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'app', 'go', 'run', 'soma.go']  

- id: "Rodando o binario gerado"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'app', 'go/src/app/soma']  

- id: "Rodando o test criad para a soma"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'app', 'go', 'test']

- id: "Gerar build da imagem"
  name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/desafio-ci:latest'
  - '-t'
  - 'gcr.io/$PROJECT_ID/desafio-ci:0.0.1'
  - '.'